-- Additional Challenge Templates for Goal Transformation App
-- Run this in Supabase SQL Editor to add more challenges

-- LANGUAGES Domain (id=1)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-lang-004', 1, 'Label Everything', 'Put sticky notes with target language words on 20 objects around your home', 'Write the word in your target language on sticky notes and place them on common objects: door, window, fridge, mirror, etc.', 30, 2, FALSE, '["Environmental immersion reinforces vocabulary through repeated exposure"]', '["vocabulary", "environmental", "beginner"]', 'Place 20+ labeled sticky notes around your home'),
('tpl-lang-005', 1, 'Podcast Shadowing', 'Listen to a 10-minute podcast and repeat sentences aloud immediately after hearing them', 'Find a podcast in your target language. Pause after each sentence and repeat it, mimicking pronunciation and rhythm.', 15, 4, FALSE, '["Shadowing improves pronunciation and listening comprehension simultaneously"]', '["listening", "speaking", "intermediate"]', 'Shadow for 10 minutes without giving up'),
('tpl-lang-006', 1, 'Dream Journal', 'Write about your dreams or daily thoughts in your target language for 10 minutes', 'Free-write without worrying about mistakes. The goal is to think and express in the target language.', 10, 4, FALSE, '["Free writing builds fluency by reducing self-editing"]', '["writing", "fluency", "intermediate"]', 'Write continuously for 10 minutes'),
('tpl-lang-007', 1, 'Order Food in Target Language', 'Call a restaurant and make a reservation or order food in your target language', 'Find a restaurant that speaks your target language. Call and conduct the entire conversation in that language.', 15, 8, TRUE, '["Real-world stakes dramatically increase retention and confidence"]', '["speaking", "real-world", "advanced"]', 'Complete a real phone conversation'),
('tpl-lang-008', 1, 'Song Translation', 'Listen to a song and translate the lyrics without looking them up', 'Pick a song in your target language. Listen multiple times and write down what you understand before checking.', 20, 5, FALSE, '["Music engages emotional memory, enhancing vocabulary retention"]', '["listening", "vocabulary", "intermediate"]', 'Translate at least 50% of a song correctly')
ON CONFLICT DO NOTHING;

-- MOBILITY Domain (id=2)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-mob-003', 2, 'Wall Slide Assessment', 'Perform 10 wall angels with your entire back touching the wall', 'Stand with back flat against wall. Slowly raise arms overhead while keeping contact with wall throughout.', 10, 4, FALSE, '["Wall slides reveal and improve shoulder mobility restrictions"]', '["shoulders", "assessment", "beginner"]', 'Complete 10 wall angels with full wall contact'),
('tpl-mob-004', 2, 'Hip Flexor Release', 'Hold a kneeling hip flexor stretch for 2 minutes on each side', 'Kneel on one knee, push hips forward gently, squeeze glute. Breathe deeply and relax into the stretch.', 5, 3, FALSE, '["Prolonged stretching triggers nervous system adaptations"]', '["hips", "stretching", "beginner"]', '2 minutes each side without breaking form'),
('tpl-mob-005', 2, 'Toe Touch Progression', 'Work toward touching your toes using the Jefferson Curl or toe touch progression', 'Start standing, slowly roll down vertebra by vertebra, reaching toward toes. Only go as far as comfortable.', 10, 5, FALSE, '["Progressive overload in flexibility creates lasting changes"]', '["hamstrings", "spine", "intermediate"]', 'Get 2cm closer than last time'),
('tpl-mob-006', 2, 'Floor Sitting Challenge', 'Sit on the floor in different positions for 30 minutes total today', 'Alternate between cross-legged, legs extended, kneeling, and squat positions while reading or watching TV.', 30, 3, FALSE, '["Ground living cultures maintain mobility into old age"]', '["hips", "lifestyle", "beginner"]', 'Accumulate 30 minutes of floor sitting'),
('tpl-mob-007', 2, 'Cold Morning Stretch', 'Do a 10-minute stretch routine immediately upon waking, before your body warms up', 'Perform gentle stretches right after getting out of bed, when muscles are still "cold".', 10, 6, TRUE, '["Cold stretching builds resilience and body awareness"]', '["morning", "discipline", "intermediate"]', 'Complete stretch within 5 minutes of waking')
ON CONFLICT DO NOTHING;

-- EMOTIONAL GROWTH Domain (id=3)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-emo-002', 3, 'Gratitude Deep Dive', 'Write 3 things you''re grateful for and explain WHY for each one in detail', 'Go beyond surface level. For each item, write 3-4 sentences about why it matters and how it affects your life.', 15, 3, FALSE, '["Detailed gratitude practice increases life satisfaction by 25%"]', '["gratitude", "writing", "beginner"]', 'Write detailed explanations for 3 gratitude items'),
('tpl-emo-003', 3, 'Anxiety Reframe', 'When you feel anxious today, write down the anxious thought and a more balanced alternative', 'Catch anxious thoughts. Write: "I''m thinking X, but a more balanced view is Y."', 30, 5, FALSE, '["Cognitive reframing reduces anxiety symptoms by 40%"]', '["anxiety", "cognitive", "intermediate"]', 'Reframe at least 3 anxious thoughts'),
('tpl-emo-004', 3, 'Vulnerability Practice', 'Share something personal with someone you trust that you''ve never told them before', 'Choose carefully and share something meaningful. It doesn''t have to be dramatic, just authentic.', 20, 7, TRUE, '["Vulnerability deepens connection and builds emotional resilience"]', '["vulnerability", "connection", "advanced"]', 'Have one vulnerable conversation'),
('tpl-emo-005', 3, 'Anger Processing', 'When frustrated today, pause for 90 seconds before responding', 'Use the 90-second rule: physiological anger dissipates in 90 seconds if you don''t feed it.', 0, 6, FALSE, '["The 90-second rule is based on neuroscience of emotion regulation"]', '["anger", "regulation", "intermediate"]', 'Successfully pause before reacting 3 times'),
('tpl-emo-006', 3, 'Self-Compassion Letter', 'Write a letter to yourself as if you were writing to a good friend going through the same situation', 'Address your current struggles with the kindness you''d show a friend. Be supportive, not critical.', 20, 4, FALSE, '["Self-compassion activates the caregiving system, reducing cortisol"]', '["self-compassion", "writing", "intermediate"]', 'Complete a full self-compassion letter')
ON CONFLICT DO NOTHING;

-- RELATIONSHIPS Domain (id=4)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-rel-001', 4, 'Appreciation Text', 'Send a specific appreciation message to 3 people explaining exactly what you value about them', 'Be specific: "I appreciate how you always..." is better than "Thanks for everything."', 15, 2, FALSE, '["Expressing appreciation strengthens relationships and boosts both parties'' wellbeing"]', '["appreciation", "connection", "beginner"]', 'Send 3 specific appreciation messages'),
('tpl-rel-002', 4, 'Active Listening Practice', 'In your next conversation, focus only on understanding without formulating your response', 'Let the other person finish completely. Paraphrase what they said before responding.', 20, 4, FALSE, '["Active listening increases relationship satisfaction by 31%"]', '["listening", "presence", "intermediate"]', 'Have one conversation with full attention'),
('tpl-rel-003', 4, 'Reconnect with Someone', 'Reach out to someone you haven''t talked to in over 6 months', 'Send a message or call someone you''ve lost touch with. No agenda, just genuine reconnection.', 15, 5, FALSE, '["Maintaining weak ties provides diverse social support"]', '["reconnection", "network", "intermediate"]', 'Have a meaningful exchange with an old contact'),
('tpl-rel-004', 4, 'Question Game', 'Ask someone 5 deep questions from a list of conversation starters', 'Use questions like: "What''s a belief you held strongly that you''ve changed?" or "What are you most proud of?"', 30, 5, FALSE, '["Deep questions accelerate relationship intimacy"]', '["conversation", "depth", "intermediate"]', 'Complete 5-question conversation'),
('tpl-rel-005', 4, 'Public Compliment', 'Give a genuine compliment to a stranger in public', 'Compliment something specific: their style, energy, or something they''re doing. Be genuine and brief.', 5, 7, TRUE, '["Giving compliments to strangers builds social courage"]', '["social", "courage", "advanced"]', 'Give one genuine compliment to a stranger')
ON CONFLICT DO NOTHING;

-- PHYSICAL HEALTH Domain (id=5)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-fit-001', 5, 'Movement Snacks', 'Do 5 micro-workouts throughout the day: 10 squats, pushups, or lunges each', 'Set 5 alarms. When they go off, do 10 reps of any bodyweight exercise immediately.', 15, 2, FALSE, '["Exercise snacking maintains metabolic health as effectively as continuous exercise"]', '["movement", "habit", "beginner"]', 'Complete 5 movement snacks'),
('tpl-fit-002', 5, 'Stair Challenge', 'Take stairs instead of elevators all day and add an extra flight each time', 'Every time you encounter stairs, take them. If possible, go up one extra floor.', 0, 3, FALSE, '["Incidental exercise accumulates significant health benefits"]', '["cardio", "lifestyle", "beginner"]', 'Take stairs exclusively for one day'),
('tpl-fit-003', 5, 'Plank Progression', 'Hold a plank for as long as you can, rest, then try to beat it', 'Start plank. Track time. Rest 2 minutes. Try again aiming for 10+ seconds more.', 10, 5, FALSE, '["Progressive overload builds muscular endurance"]', '["core", "strength", "intermediate"]', 'Beat your first plank time on the second attempt'),
('tpl-fit-004', 5, 'Walking Meeting', 'Take a phone call or have a meeting while walking outside', 'Schedule a call and go for a walk during it. Aim for at least 15 minutes of walking.', 20, 3, FALSE, '["Walking meetings increase creativity by 60%"]', '["walking", "productivity", "beginner"]', 'Complete one walking meeting'),
('tpl-fit-005', 5, 'Burpee Challenge', 'Complete 50 burpees in as few sets as possible', 'Do as many burpees as you can, rest when needed, continue until you hit 50 total.', 20, 8, TRUE, '["High-intensity challenges build mental and physical resilience"]', '["hiit", "challenge", "advanced"]', 'Complete 50 burpees')
ON CONFLICT DO NOTHING;

-- TOLERANCE Domain (id=6)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-tol-002', 6, 'Delayed Gratification', 'When you want to check social media, wait 10 minutes before allowing yourself', 'Every time you reach for your phone to scroll, set a 10-minute timer first.', 0, 4, FALSE, '["Delayed gratification builds prefrontal cortex regulation"]', '["discipline", "phones", "intermediate"]', 'Delay phone checking 5 times'),
('tpl-tol-003', 6, 'Hunger Tolerance', 'Skip one meal intentionally and observe the experience without judgment', 'Skip breakfast or lunch. Notice hunger sensations without labeling them as bad.', 0, 6, FALSE, '["Intermittent fasting builds metabolic flexibility and mental discipline"]', '["fasting", "awareness", "intermediate"]', 'Skip one meal mindfully'),
('tpl-tol-004', 6, 'Silence Challenge', 'Spend 2 hours without any audio input: no music, podcasts, TV, or conversation', 'Be in silence. Notice what comes up. Use the time for thinking or simple activities.', 120, 5, FALSE, '["Silence builds comfort with self and reduces anxiety"]', '["silence", "presence", "intermediate"]', '2 hours of complete silence'),
('tpl-tol-005', 6, 'Ask for a Discount', 'Ask for a discount or better deal somewhere you normally wouldn''t', 'At a store, café, or service, politely ask if there''s any discount available.', 5, 7, TRUE, '["Rejection therapy builds social courage and adaptability"]', '["rejection", "social", "advanced"]', 'Ask for a discount at least once'),
('tpl-tol-006', 6, 'Wake Up Immediately', 'When your alarm goes off, get out of bed within 5 seconds', 'No snooze. Count 5-4-3-2-1 and physically get up. Make this non-negotiable.', 0, 5, FALSE, '["The 5-second rule hijacks hesitation and builds discipline"]', '["morning", "discipline", "intermediate"]', 'Get up within 5 seconds of alarm')
ON CONFLICT DO NOTHING;

-- SKILLS Domain (id=7)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-skl-001', 7, 'Deliberate Practice Session', 'Practice one specific skill for 25 minutes with full focus, no distractions', 'Use Pomodoro technique. Work on the hardest part of your skill, not just what''s fun.', 25, 4, FALSE, '["Deliberate practice is 10x more effective than casual practice"]', '["focus", "learning", "intermediate"]', 'Complete focused 25-minute session'),
('tpl-skl-002', 7, 'Teach Someone', 'Explain a skill or concept you''re learning to someone who knows nothing about it', 'Find someone and teach them the basics. This reveals gaps in your understanding.', 20, 5, FALSE, '["Teaching others solidifies learning (the Feynman Technique)"]', '["teaching", "learning", "intermediate"]', 'Teach one concept to someone'),
('tpl-skl-003', 7, 'Watch and Analyze', 'Watch an expert perform your skill for 15 minutes, taking notes on technique', 'Find a video of an expert. Pause, rewind, and note specific techniques they use.', 15, 3, FALSE, '["Observational learning activates mirror neurons"]', '["observation", "learning", "beginner"]', 'Fill one page of technique notes'),
('tpl-skl-004', 7, 'Failure Quota', 'Intentionally try difficult variations of your skill until you fail 5 times', 'Push beyond your comfort zone. Failure means you''re at your growth edge.', 20, 6, FALSE, '["Error-driven learning is more effective than success-only practice"]', '["failure", "growth", "intermediate"]', 'Fail at least 5 times at hard variations'),
('tpl-skl-005', 7, 'Public Performance', 'Share your work or perform your skill for at least one other person', 'Could be in person or online. The key is getting feedback on real execution.', 15, 8, TRUE, '["Performance anxiety, when embraced, accelerates skill development"]', '["performance", "feedback", "advanced"]', 'Share your work publicly')
ON CONFLICT DO NOTHING;

-- HABITS Domain (id=8)
INSERT INTO "ChallengeTemplate" ("id", "domainId", "title", "description", "instructions", "durationMinutes", "difficulty", "isRealityShift", "scientificReferences", "tags", "successCriteria") VALUES
('tpl-hab-002', 8, 'Temptation Bundling', 'Pair something you want to do with something you should do', 'Only allow yourself to do the enjoyable thing while doing the important thing. Example: podcasts only while exercising.', 30, 3, FALSE, '["Temptation bundling increases follow-through by 51%"]', '["motivation", "pairing", "beginner"]', 'Create and use one temptation bundle'),
('tpl-hab-003', 8, 'Environment Design', 'Modify your environment to make your desired habit easier or your bad habit harder', 'Add friction to bad habits, remove friction from good ones. Redesign one space.', 20, 4, FALSE, '["Environment design is more powerful than willpower"]', '["environment", "setup", "intermediate"]', 'Make one environment change'),
('tpl-hab-004', 8, 'Implementation Intention', 'Write down exactly when, where, and how you''ll perform your habit tomorrow', 'Use format: "I will [BEHAVIOR] at [TIME] in [LOCATION]." Be extremely specific.', 10, 2, FALSE, '["Implementation intentions double follow-through rates"]', '["planning", "specific", "beginner"]', 'Write a specific implementation intention'),
('tpl-hab-005', 8, 'Accountability Photo', 'Take a photo as proof of completing your habit and share it with someone', 'After doing your habit, snap a photo and send it to an accountability partner.', 5, 4, FALSE, '["Social accountability increases habit adherence"]', '["accountability", "social", "intermediate"]', 'Share proof of habit completion'),
('tpl-hab-006', 8, 'Habit Reflection', 'At end of day, rate how well you stuck to your intentioned habits from 1-10', 'Review what you planned vs what you did. Score honestly. Note what got in the way.', 10, 3, FALSE, '["Daily reflection increases habit success rates"]', '["reflection", "tracking", "beginner"]', 'Complete honest daily habit review')
ON CONFLICT DO NOTHING;
